# Calculation formula: number of cookies * nums equals number of tasks
nums: 10
# proxy config; Within 300G 1.5U/G Above 300G 1.2U/G; For more offers contact: wuaiyiyun2022@163.com
proxy_uname: ""
proxy_pwd: ""